### ISSUE TITLE
bazel.buildifierPath doesn't allow for relative paths

### ISSUE THREAD

**Issue by dapirian** [devoncarew/bazel-code#14]
There's no way to give a relative path to buildifier, which I have commited into my repo. Other extensions either just allow relative paths, or allow for something like `${workspaceRoot}/my/path/to/buildifier`

**Comment by ShivvaSubramani** [comment]
Following up with dapirian's request,  bazel.buildifierPath works only with absolute path. Setting "bazel.buildifierPath": "$workspaceFolder/bin/buildifier" fails with error: "buildifier path is incorrect: $workspaceFolder/bin/buildifier" because this bazel extension cannot resolve $workspaceFolder variable. 
Updating this bazel extension to resolve "$workspaceFolder" variable will be helpful to add this to our project and release it to all our developers. 
Thanks,
Shivva

**Comment by ShivvaSubramani** [comment]
Adding to my previous comment: 

This issue can be fixed by updating https://github.com/devoncarew/bazel-code/blob/master/src/extension.ts line 26 to resolve $workspaceFolder in buildifierPath before calling  cp.execFile(buildifierPath, ["-mode=fix", document.fileName]).

**Comment by joshclimacell** [comment]
Also, am I the only one who seems to find that the extension takes several seconds to execute `buildifier`, even though running `buildifier` from the terminal executes instantaneously?

**Comment by devoncarew** [comment]
Closing this as we're deprecating this extension in favor of https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel.
